debug: false # spring boot log 설정
management:
  endpoints:
    web:
      exposure:
        include: "*" # actuator 숨겨진 endpoint 노출

logging:
  level: # 모듈 별 로그 레벨 설정
    com.nightdiver.javaboard: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER}
  jpa:
    defer-datasource-initialization: true # datasource 초기화를 늦게 하기 위해 설정
    open-in-view: false #
    show-sql: true
    hibernate:
      ddl-auto: create #
    properties:
        hibernate:
          format_sql: true
          default_batch_fetch_size: 100 # 조인 등으로 여러 튜플 가져올 때 배치 사이즈만큼 벌크 처리한다. N+1 문제 해결

  h2:
    console:
      enabled: false
  sql:
    init: # data.sql 사용 위함
      mode: always # Embedded: 테스트, Always: 운영에도, Never: ???
  # thymeleaf.cache: false # thymeleaf 캐시 사용 안함
  data:
    rest:
      base-path: /api # rest api base path
      detection-strategy: annotated # rest api 자동 생성 전략
      # all: 모든 repository 를 잡아 API 로 노출.
      # annotated: @(Repository)RestResource 를 사용한 것만 API 로 노출
      # visibility: public repository API 로 노출
      # default: 모든 public interface. @(Repository)RestResource 의 exported flag 고려함
  config:
    import: classpath:/secrets.yml # secrets.yml 파일을 import
#--- 줄 세 개로 여러 프로파일 설정 가능

#spring:
#  config:
#    activate:
#      on-profile: testdb
#  datasource:
#    url: jdbc:h2:mem:board;mode=mysql
#    driver-class-name: org.h2.Driver
#  sql:
#    init:
#      mode: always
#  test.database.replace: none # 테스트용 임의 DB 사용 안함

