debug: false # ???? ??? ?? ?? ? ?? ??? ?. ??? ?? ?? ???
management:
  endpoints:
    web:
      exposure:
        include: "*" # ?? ????? ??

logging:
  level:
    com.nightdiver.javaboard: debug # ??? ??? ??
    org.springframework.web.servlet: debug # ??? ??? ??
    org.hibernate.type.descriptor.sql.BasicBinder: trace # ???? ??? ??

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER}
  jpa:
    defer-datasource-initialization: true # ???? ??? ??
    open-in-view: false # ????? ???. ??? ???? ????
    show-sql: true
    hibernate:
      ddl-auto: create # ?????? ?? ? ??? ??
    properties:
        hibernate:
          format_sql: true # SQL ??? ? ?? ???? ???? ??? ???.
          default_batch_fetch_size: 100 # ??? ????? ??? ? ?? bulk? ???
          # ???? ??? Row ?? 10? ?????? ??? 10??? ???? ? ??? (N+1 ??)
          # ?? ???? ?? id in ??? ? ?? ??? ? ?? ?? ??
          # ??? 100? ?? ?? 100?? ??? ?? bulk? ???? ? ??.
  h2:
    console:
      enabled: false # h2 ??? ???? ???.
  sql:
    init: # data.sql ?? ??
      mode: always # Embedded: ???? ????(???), Always: ??(??), Never: ???
  # thymeleaf.cache: false # ??? ??? ???? ???.
  data:
    rest:
      base-path: /api # rest api? ?? ??? /api? ??
  config:
    import: classpath:/secrets.yml # secrets.yml ??? ?????.
#--- # ?? ?? ???? ??? ??

#spring:
#  config:
#    activate:
#      on-profile: testdb
#  datasource:
#    url: jdbc:h2:mem:board;mode=mysql
#    driver-class-name: org.h2.Driver
#  sql:
#    init:
#      mode: always
#  test.database.replace: none # ???? ??????? ???? ???.

